version: '3.1'
services:
    postgres:
        image: postgres
        container_name: 'postgres'
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=masterkey
            - POSTGRES_INIT_SCRIPT=/entrypoint/init.sh
            - POSTGRES_DB=personal
        volumes:
            - ./database/postgres:/docker-entrypoint-initdb.d
        ports:
            - '5432:5432'

        networks:
            my-network:
                ipv4_address: 192.168.3.4
    firebird:
        image: jacobalberty/firebird:v3.0
        container_name: 'firebird'
        environment:
            - ISC_PASSWORD=masterkey
            - FIREBIRD_DATABASE=facturacion.fdb
            - EnableLegacyClientAuth=true
            - FIREBIRD_INIT_SCRIPT=/entrypoint/init.sh
        ports:
            - '3062:3050'
        volumes:
            - ./database/firebird:/entrypoint
        networks:
            my-network:
                ipv4_address: 192.168.3.3
    switch-server:
        image: mgimenezdev/switch-server
        container_name: 'switch-server'
        ports:
            - '5000:5000'
        networks:
            my-network:
                ipv4_address: 192.168.3.102
networks:
    my-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.3.0/24
